# STATS 507 · Week5-1: NumPy practice — Solutions

Completed solutions for the four in-class questions. Run the cells in order. Each question retains its two short checks.

Rows represent stores; columns represent three days, from oldest to newest. Negative values are recording errors.

In [1]:
import numpy as np

stores = np.array(["A", "B", "C", "D"])
sales = np.array([
    [10, -2, 20],  # Store A
    [ 5, 25,  0],  # Store B
    [20, 10, 30],  # Store C
    [-3,  0, 20],  # Store D
])

print(sales)

[[10 -2 20]
 [ 5 25  0]
 [20 10 30]
 [-3  0 20]]


## 1. Inspect and select

1. Display `sales.shape` and explain what each entry represents.
2. Select Day 2 sales for all stores as a one-dimensional array named `day2`.
3. Select the last two days for the first two stores as a two-dimensional array named `recent_sales`.

In [2]:
# Four stores (rows), three days (columns).
print("Shape:", sales.shape)

day2 = sales[:, 1]
print("Day 2:", day2)

recent_sales = sales[:2, 1:]
print("First two stores, last two days:\n", recent_sales)

Shape: (4, 3)
Day 2: [-2 25 10  0]
First two stores, last two days:
 [[-2 20]
 [25  0]]


In [3]:
# Quick check for Question 1
assert np.array_equal(day2, [-2, 25, 10, 0])
assert np.array_equal(recent_sales, [[-2, 20], [25, 0]])
print("Question 1 passed!")

Question 1 passed!


## 2. Find and fix recording errors 

1. Create a Boolean array `invalid` that identifies negative entries. Use it to display the invalid values.
2. Create `cleaned` as a copy of `sales` and replace all negative entries with zero.
3. Display `cleaned` and check that `sales` still contains the original values.

**Explain briefly:** Why use `sales.copy()` instead of `cleaned = sales`?

In [4]:
invalid = sales < 0
print("Invalid values:", sales[invalid])

cleaned = sales.copy()
cleaned[invalid] = 0

print("Cleaned sales:\n", cleaned)
print("Original sales:\n", sales)

Invalid values: [-2 -3]
Cleaned sales:
 [[10  0 20]
 [ 5 25  0]
 [20 10 30]
 [ 0  0 20]]
Original sales:
 [[10 -2 20]
 [ 5 25  0]
 [20 10 30]
 [-3  0 20]]


**Explanation:** `sales.copy()` creates an independent array, so changing `cleaned` does not change `sales`. With `cleaned = sales`, both names refer to the same array; assigning through either name changes that shared array.

In [5]:
# Quick check for Question 2
assert np.array_equal(cleaned, [[10, 0, 20], [5, 25, 0], [20, 10, 30], [0, 0, 20]])
assert np.array_equal(sales, [[10, -2, 20], [5, 25, 0], [20, 10, 30], [-3, 0, 20]])
print("Question 2 passed!")

Question 2 passed!


## 3. Update the report

Some sales were omitted: **2 per store on Day 1, 0 on Day 2, and 1 on Day 3**.

1. Add the provided `extra` array to `cleaned` to create `updated`.
2. Compute `store_totals`: one total per store across all days.
3. Compute `day_totals`: one total per day across all stores.

Choose the appropriate `axis` for each sum. Explain why `extra` can be added to every row even though its shape differs from `cleaned.shape`.

**Quick check:** Store A's updated total should be **33**.

In [6]:
extra = np.array([2, 0, 1])
updated = cleaned + extra

store_totals = updated.sum(axis=1)
day_totals = updated.sum(axis=0)

print("Updated sales:\n", updated)
print("Store totals:", store_totals)
print("Day totals:", day_totals)

Updated sales:
 [[12  0 21]
 [ 7 25  1]
 [22 10 31]
 [ 2  0 21]]
Store totals: [33 33 63 23]
Day totals: [43 35 74]


**Explanation:** `axis=1` sums across the days, leaving one total per store. `axis=0` sums across the stores, leaving one total per day.

`cleaned` has shape `(4, 3)` and `extra` has shape `(3,)`. Their trailing dimensions match, so broadcasting applies the three daily additions to each of the four rows.

In [7]:
# Quick check for Question 3
assert np.array_equal(store_totals, [33, 33, 63, 23])
assert np.array_equal(day_totals, [43, 35, 74])
print("Question 3 passed!")

Question 3 passed!


## 4. Select stores for a follow-up
Using `updated` and `store_totals`, find stores that satisfy **both** conditions:

- Their total sales are **at least 25**.
- Their Day 3 sales are **at least 15**.

Create one Boolean mask called `selected`. Use it to save the qualifying store names as `selected_stores` and their rows from `updated` as `selected_sales`, preserving the original order. Display both arrays.

**Think before running:** Which stores do you expect to qualify?

*Hint: Combine Boolean arrays with `&` and put parentheses around each comparison.*

In [8]:
# Prediction: A and C qualify.
# B meets only the total-sales condition; D meets only the Day 3 condition.
selected = (store_totals >= 25) & (updated[:, 2] >= 15)

selected_stores = stores[selected]
selected_sales = updated[selected]

print("Selected mask:", selected)
print("Selected stores:", selected_stores)
print("Selected sales:\n", selected_sales)

Selected mask: [ True False  True False]
Selected stores: ['A' 'C']
Selected sales:
 [[12  0 21]
 [22 10 31]]


In [9]:
# Quick check for Question 4
assert np.array_equal(selected_stores, ["A", "C"])
assert np.array_equal(selected_sales, [[12, 0, 21], [22, 10, 31]])
print("Question 4 passed!")

Question 4 passed!
