# Week 5.1 · NumPy walkthrough
Run top to bottom; predict values and shapes before executing. Short examples follow the lecture.

Slide references use printed slide numbers. The pairwise-distance extension is optional.

In [36]:
import numpy as np

## 1. Lists vs. arrays · slide 6

In [37]:
values = [1, 2, 3]
a = np.array(values)
# Lists repeat; arrays multiply each numerical value.
print("List * 2: ", values * 2)
print("Array * 2:", a * 2)
# List addition concatenates; array addition adds matching entries.
print("List + list:  ", values + values)
print("Array + array:", a + a)

List * 2:  [1, 2, 3, 1, 2, 3]
Array * 2: [2 4 6]
List + list:   [1, 2, 3, 1, 2, 3]
Array + array: [2 4 6]


### A calculation on every value

In [38]:
prices = [10, 20, 30]
# The comprehension visits one price at a time.
print([price * 1.08 for price in prices])
# Vectorization: apply the same 8% increase to the entire array.
print(np.array(prices) * 1.08)

[10.8, 21.6, 32.400000000000006]
[10.8 21.6 32.4]


## 2. Dtypes and precision · slides 8–11

In [39]:
a = np.array([1, 2, 3])
# Explicit dtype: store every entry as a 64-bit floating-point value.
b = np.array([1, 2, 3], dtype=np.float64)
print(a, a.dtype)
print(b, b.dtype)
print(np.array([1, 2.5]))  # One dtype for all elements

[1 2 3] int64
[1. 2. 3.] float64
[1.  2.5]


In [40]:
x = np.float64(3.1415)
y = np.float32(3.1415)
# Show extra digits to reveal differences hidden by normal printing.
print("Stored values:", format(float(x), ".20g"), format(float(y), ".20g"))
# Casting to float64 cannot recover precision already lost in float32.
print("Equal after casting?", x == np.float64(y))
# Approximate comparison uses tolerances instead of exact equality.
print("Close?", np.isclose(x, y))

Stored values: 3.1415000000000001812 3.1414999961853027344
Equal after casting? False
Close? True


In [41]:
print(x)

3.1415


### Casting and assignment

In [42]:
measurements = np.array([1.2, 2.8, 3.5])
# Integer conversion truncates toward zero; it does not round.
print("Cast to int:", measurements.astype(int))
counts = np.array([1, 2, 3])
# Assignment retains the array dtype, so 2.9 is stored as 2.
counts[0] = 2.9
print("Integer array after assignment:", counts)
# itemsize counts bytes per element: 4 for float32, 8 for float64.
print("float32 bytes/value:", np.dtype(np.float32).itemsize)
print("float64 bytes/value:", np.dtype(np.float64).itemsize)

Cast to int: [1 2 3]
Integer array after assignment: [2 2 3]
float32 bytes/value: 4
float64 bytes/value: 8


## 3. Creating arrays · slides 12–15

In [43]:
# A single number gives a 1D shape; a tuple gives multiple axis lengths.
#print(np.zeros((5,2)))
#print(np.ones((2, 3)))
#print(np.arange(0, 12, 1))   # Step size; stop excluded
print(np.linspace(0, 1, 5)) # Number of points; endpoints included

[0.   0.25 0.5  0.75 1.  ]


### More ways to choose endpoints

In [44]:
# One argument means start at 0; the stop is excluded.
print(np.arange(5))


print(np.arange(2, 6))
# A negative step moves backward: 5, 3, 1.
print(np.arange(5, 0, -2))
# Five equally spaced points in [0, 1), excluding 1.
print(np.linspace(0, 1, 5, endpoint=False))
# Create the requested shape and fill every entry with 7.
print(np.full((2, 3), 7))

[0 1 2 3 4]
[2 3 4 5]
[5 3 1]
[0.  0.2 0.4 0.6 0.8]
[[7 7 7]
 [7 7 7]]


In [45]:
# eye places ones on the main diagonal; other entries are zero.
print(np.eye(3))
print(np.eye(3, 5))
# A 1D input to diag creates a 2D diagonal array.
print(np.diag([1, 2, 3]))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]


### Extracting a diagonal

In [46]:
matrix = np.arange(1, 10).reshape(3, 3)
print(matrix)
# A 2D input to diag extracts entries instead of constructing a matrix.
print("Main diagonal:", np.diag(matrix))
print("Above main diagonal:", np.diag(matrix, k=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Main diagonal: [1 5 9]
Above main diagonal: [2 6]


In [47]:
sample = np.array([[1, 2, 3], [4, 5, 6]])
# The _like constructors reuse both shape and dtype by default.
print(np.full_like(sample, 7))
print(np.zeros_like(sample))
print(np.ones_like(sample))
print(np.full_like(sample, 0.5))              # Inherits integer dtype
# Override dtype to retain the fractional fill value.
print(np.full_like(sample, 0.5, dtype=float))

[[7 7 7]
 [7 7 7]]
[[0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]]
[[0 0 0]
 [0 0 0]]
[[0.5 0.5 0.5]
 [0.5 0.5 0.5]]


## 4. Shape, ndim, size · slides 10, 16
**Predict:** What is the difference between `size` and `len`?

In [48]:
a = np.arange(10).reshape(2, 5)
print(a)
# shape lists axis lengths; ndim counts axes.
print("shape:", a.shape, "ndim:", a.ndim)
# size counts all entries; len counts entries along the first axis.
print("size:", a.size, "len:", len(a), "dtype:", a.dtype)

[[0 1 2 3 4]
 [5 6 7 8 9]]
shape: (2, 5) ndim: 2
size: 10 len: 2 dtype: int64


In [49]:
b = np.zeros((5,2,3))
print(b.dtype)

float64


In [50]:
v = np.array([1, 2, 3])
print("1D:   ", v.shape)
# None inserts a length-one axis: (3,) becomes (1, 3).
print("Row:  ", v[None, :].shape)
# Inserting the axis at the end gives (3, 1).
print("Column:", v[:, None].shape)

1D:    (3,)
Row:   (1, 3)
Column: (3, 1)


### Reshape: infer one dimension

In [51]:
flat = np.arange(12)
# Reshape preserves the total number of elements.
print(flat.reshape(3, 4))
print(flat.reshape(2, -1))  # Infer 6 columns
# This intentionally fails: 12 elements cannot fill a (5, 3) array.
try:
    flat.reshape(5, 3)
except ValueError as error:
    print(error)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
cannot reshape array of size 12 into shape (5,3)


### A 3D array: two tables

In [52]:
# Interpret the axes as (table, row, column).
cube = np.arange(24).reshape(2, 3, 4)
print(cube)
print("shape / ndim / size:", cube.shape, cube.ndim, cube.size)
print("Second table:\n", cube[1])
# All indices are zero-based: this is the last entry of the second table.
print("Table 1, row 2, column 3:", cube[1, 2, 3])

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
shape / ndim / size: (2, 3, 4) 3 24
Second table:
 [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
Table 1, row 2, column 3: 23


## 5. Slicing · slide 18
**Predict:** Do `a[0]` and `a[0:1]` have the same shape?

In [53]:
a = np.arange(1, 13).reshape(3, 4)
print(a)
# Rows 0 and 1; columns 1 and 2. Slice stops are excluded.
print("Slice:\n", a[:2, 1:3])
# The colon keeps all rows; -1 selects the final column.
print("Last column:", a[:, -1])
# An integer index removes an axis; a slice keeps that axis.
print("Shapes:", a[0].shape, a[0:1].shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Slice:
 [[2 3]
 [6 7]]
Last column: [ 4  8 12]
Shapes: (4,) (1, 4)


### 1D slices: start, stop, step

In [54]:
line = np.arange(10)
print("Middle:", line[2:7])
# Omitted start/stop span the full axis; step=2 skips alternate entries.
print("Every other:", line[::2])
# Negative indices count from the end.
print("Last three:", line[-3:])
# A negative step reverses traversal.
print("Reverse:", line[::-1])

Middle: [2 3 4 5 6]
Every other: [0 2 4 6 8]
Last three: [7 8 9]
Reverse: [9 8 7 6 5 4 3 2 1 0]


### 2D slices and assignment

In [55]:
grid = np.arange(1, 13).reshape(3, 4)
# First selector controls rows; second controls columns.
print("Every other column:\n", grid[:, ::2])
print("Reverse row order:\n", grid[::-1, :])
print("Column shapes:", grid[:, 1].shape, grid[:, 1:2].shape)
# Assign one value to a block: first two rows, last two columns.
grid[:2, -2:] = 0
print("After block assignment:\n", grid)

Every other column:
 [[ 1  3]
 [ 5  7]
 [ 9 11]]
Reverse row order:
 [[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]
Column shapes: (3,) (3, 1)
After block assignment:
 [[ 1  2  0  0]
 [ 5  6  0  0]
 [ 9 10 11 12]]


In [56]:
a = np.arange(1, 13).reshape(3, 4)
# Basic slicing shares the original data rather than making a new copy.
view = a[:2, 1:3]
# copy() creates independent storage.
copied = a[:2, 1:3].copy()
# This location corresponds to a[0, 1], so the original also changes.
view[0, 0] = 99
print("Original changed:\n", a)
print("Independent copy:\n", copied)

Original changed:
 [[ 1 99  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Independent copy:
 [[2 3]
 [6 7]]


## 6. Integer and Boolean indexing · slides 19–20

In [57]:
a = np.array([[1, 2], [3, 4], [5, 6]])
# Match each row index with the column index at the same position.
print(a[[0, 1, 2], [0, 1, 0]])  # Pairs: (0,0), (1,1), (2,0)
print(a[[0, 2]])                # Whole rows

[1 4 5]
[[1 2]
 [5 6]]


### Reorder, repeat, or select a rectangle

In [58]:
grid = np.arange(1, 13).reshape(3, 4)
print("Reordered/repeated rows:\n", grid[[2, 0, 2]])
# Two index lists select two pairs, not a 2-by-2 rectangle.
print("Paired positions:", grid[[0, 2], [1, 3]])
# ix_ forms a grid of indices: every selected row with every selected column.
print("All row-column combinations:\n", grid[np.ix_([0, 2], [1, 3])])

Reordered/repeated rows:
 [[ 9 10 11 12]
 [ 1  2  3  4]
 [ 9 10 11 12]]
Paired positions: [ 2 12]
All row-column combinations:
 [[ 2  4]
 [10 12]]


In [59]:
# Comparing each entry produces a Boolean array of the same shape.
mask = a > 2
print(mask)
# A full-shape mask returns matching values in a 1D array.
print("Selected:", a[mask])
print("Shapes:", mask.shape, a[mask].shape)

[[False False]
 [ True  True]
 [ True  True]]
Selected: [3 4 5 6]
Shapes: (3, 2) (4,)


### Filter entire rows

In [60]:
scores = np.array([[80, 90], [60, 75], [95, 85]])
# Test only column 0: one True/False decision per student.
keep = scores[:, 0] >= 80
print("Row mask:", keep)
# A 1D row mask keeps whole rows; a full-shape mask keeps individual values.
print("Selected students:\n", scores[keep])
print("Selected individual scores:", scores[scores >= 80])

Row mask: [ True False  True]
Selected students:
 [[80 90]
 [95 85]]
Selected individual scores: [80 90 95 85]


### Advanced indexing returns a copy

In [61]:
original = np.arange(6)
# Integer-array indexing retrieves a copy, unlike a basic slice.
selected = original[[1, 3]]
# Only the copy changes here.
selected[0] = 99
print("Original:", original)
print("Selected copy:", selected)
original[[1, 3]] = -1  # Direct indexed assignment updates the original
print("After assignment:", original)

Original: [0 1 2 3 4 5]
Selected copy: [99  3]
After assignment: [ 0 -1  2 -1  4  5]


## 7. Boolean operations · slides 21–22
Use `&`, `|`, and `~` for Boolean arrays; parenthesize comparisons.

In [62]:
x = np.arange(10)
print("All > 7?", np.all(x > 7))
print("Any > 7?", np.any(x > 7))
# Stack two conditions: shape (2, 10).
conditions = np.array([x > 7, x < 2])
print("Conditions:\n", conditions)
# Reduce across the two conditions: one result for each value of x.
print("axis=0:", np.any(conditions, axis=0))
# Reduce across ten values: one result for each condition.
print("axis=1:", np.any(conditions, axis=1))

All > 7? False
Any > 7? True
Conditions:
 [[False False False False False False False False  True  True]
 [ True  True False False False False False False False False]]
axis=0: [ True  True False False False False False False  True  True]
axis=1: [ True  True]


In [63]:
print(x[np.logical_and(x > 3, x < 7)])
# Parentheses build each comparison before & combines the masks.
print(x[(x > 3) & (x < 7)])
print(x[(x < 3) | (x > 7)])
# XOR keeps entries satisfying exactly one of the conditions.
print(x[np.logical_xor(x > 3, x < 7)])
# ~ reverses each Boolean value; here it keeps x <= 3.
print(x[~(x > 3)])

[4 5 6]
[4 5 6]
[0 1 2 8 9]
[0 1 2 3 7 8 9]
[0 1 2 3]


### Combine conditions; keep or replace

In [64]:
temperatures = np.array([-5, 12, 25, 40])
comfortable = (temperatures >= 10) & (temperatures <= 30)
print("Keep:", temperatures[comfortable])
# where(condition, if_true, if_false) keeps the original array shape.
print("Label all:", np.where(comfortable, "comfortable", "outside range"))
print("Clip negatives:", np.where(temperatures < 0, 0, temperatures))

Keep: [12 25]
Label all: ['outside range' 'comfortable' 'comfortable' 'outside range']
Clip negatives: [ 0 12 25 40]


### all / any: one decision per student

In [65]:
scores = np.array([[80, 90], [60, 75], [95, 85]])
passed = scores >= 70
print(passed)
# axis=1 combines exam results within each student row.
print("Passed every exam:", passed.all(axis=1))
print("Passed at least one:", passed.any(axis=1))
# axis=0 combines students, leaving one decision per exam.
print("Everyone passed each exam:", passed.all(axis=0))
print("Students passing both:\n", scores[passed.all(axis=1)])

[[ True  True]
 [False  True]
 [ True  True]]
Passed every exam: [ True False  True]
Passed at least one: [ True  True  True]
Everyone passed each exam: [False  True]
Students passing both:
 [[80 90]
 [95 85]]


## 8. Elementwise arithmetic · slide 24

In [66]:
x = np.array([[1, 2], [3, 4]], dtype=float)
y = np.array([[5, 6], [7, 8]], dtype=float)
print("Add:\n", x + y)   # np.add(x, y)
print("Subtract:\n", x - y)
# * multiplies corresponding entries; it is not matrix multiplication.
print("Multiply:\n", x * y)
print("Divide:\n", x / y)
print("Square root:\n", np.sqrt(x))

Add:
 [[ 6.  8.]
 [10. 12.]]
Subtract:
 [[-4. -4.]
 [-4. -4.]]
Multiply:
 [[ 5. 12.]
 [21. 32.]]
Divide:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]
Square root:
 [[1.         1.41421356]
 [1.73205081 2.        ]]


### Powers, division, and remainders

In [67]:
values = np.array([1, 2, 3, 4])
# ** is exponentiation; ^ is a different operator.
print("Squared:", values**2)
print("Divide:", values / 2)
# // rounds the quotient down; % gives the division remainder.
print("Floor divide:", values // 2)
print("Remainder:", values % 2)
print("Even mask:", values % 2 == 0)

Squared: [ 1  4  9 16]
Divide: [0.5 1.  1.5 2. ]
Floor divide: [0 1 1 2]
Remainder: [1 0 1 0]
Even mask: [False  True False  True]


## 9. Reducing along an axis · slides 25–26
**Predict:** Which axis gives one sum per column?

In [68]:
x = np.array([[1, 2], [3, 4]])
print("All:", x.sum())
# Collapse the row axis: one sum per column.
print("axis=0:", x.sum(axis=0))
# Collapse the column axis: one sum per row.
print("axis=1:", x.sum(axis=1))
# keepdims=True leaves a length-one axis: shape (2, 1), not (2,).
print("Keep axis=1:\n", x.sum(axis=1, keepdims=True))

All: 10
axis=0: [4 6]
axis=1: [3 7]
Keep axis=1:
 [[3]
 [7]]


### Non-square data makes axes clearer

In [69]:
scores = np.array([[80, 90, 70], [60, 75, 85]])  # Students x exams
print("Exam means:", scores.mean(axis=0))
print("Student means:", scores.mean(axis=1))
print("Best score per exam:", scores.max(axis=0))
# argmax returns the zero-based position of the maximum, not its value.
print("Best exam index per student:", scores.argmax(axis=1))
print("Mean shapes:", scores.mean(axis=0).shape, scores.mean(axis=1).shape)

Exam means: [70.  82.5 77.5]
Student means: [80.         73.33333333]
Best score per exam: [80 90 85]
Best exam index per student: [1 2]
Mean shapes: (3,) (2,)


### Keeping an axis for later calculations

In [70]:
scores = np.array([[80, 90, 70], [60, 75, 85]])
# Reduce (2, 3) to (2, 1), retaining a column of row means.
row_means = scores.mean(axis=1, keepdims=True)
print("Row means:\n", row_means)
print("Shapes:", scores.shape, row_means.shape)
# Broadcast each row mean across that row's three exam scores.
print("Subtract each student's mean:\n", scores - row_means)

Row means:
 [[80.        ]
 [73.33333333]]
Shapes: (2, 3) (2, 1)
Subtract each student's mean:
 [[  0.          10.         -10.        ]
 [-13.33333333   1.66666667  11.66666667]]


## 10. Vector and matrix operations · slides 27–29

In [71]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])
# For 1D vectors, dot multiplies matching entries and sums them.
print("Vector dot product:", np.dot(v, w))
# Each matrix row is dotted with the vector.
print("Matrix @ vector:", x @ v)
print("Elementwise:\n", x * y)
# For 2D arrays, @ combines rows of the left array with columns of the right.
print("Matrix product:\n", x @ y)

Vector dot product: 219
Matrix @ vector: [29 67]
Elementwise:
 [[ 5 12]
 [21 32]]
Matrix product:
 [[19 22]
 [43 50]]


### Inner, outer, and cross products

In [72]:
u = np.array([1, 2, 3])
v3 = np.array([4, 5, 6])
print("Inner:", np.inner(u, v3))
# Outer product entry (i, j) is u[i] * v3[j]; shape (3, 3).
print("Outer:\n", np.outer(u, v3))
# The 3D cross product is perpendicular to both input vectors.
print("Cross:", np.cross(u, v3))

Inner: 32
Outer:
 [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
Cross: [-3  6 -3]


### Non-square matrix multiplication

In [73]:
A = np.arange(1, 7).reshape(2, 3)
B = np.arange(1, 13).reshape(3, 4)
print("Input shapes:", A.shape, B.shape)
# (2, 3) @ (3, 4) gives (2, 4); the inner dimensions must match.
print("A @ B:\n", A @ B)
print("Output shape:", (A @ B).shape)
print("First entry:", A[0] @ B[:, 0])
# B @ A fails because its inner dimensions are 4 and 2.
try:
    B @ A
except ValueError as error:
    print(error)

Input shapes: (2, 3) (3, 4)
A @ B:
 [[ 38  44  50  56]
 [ 83  98 113 128]]
Output shape: (2, 4)
First entry: 38
matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 4)


In [74]:
# For a 2D array, .T swaps the row and column axes.
print("Transpose:\n", x.T)
# flatten() returns an independent 1D copy in row order.
print("Flatten:", x.flatten())
print("Determinant:", np.linalg.det(x))
# An inverse requires a square, nonsingular matrix.
print("Inverse:\n", np.linalg.inv(x))

Transpose:
 [[1 3]
 [2 4]]
Flatten: [1 2 3 4]
Determinant: -2.0000000000000004
Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]


### Solve a linear system

In [75]:
A = np.array([[2., 1.], [1., 3.]])
b_rhs = np.array([5., 7.])
# Solve A @ solution = b_rhs directly, without computing an inverse.
solution = np.linalg.solve(A, b_rhs)
print("Solution:", solution)
print("A @ solution:", A @ solution)
# Check every reconstructed entry with a floating-point tolerance.
print("Correct?", np.allclose(A @ solution, b_rhs))

Solution: [1.6 1.8]
A @ solution: [5. 7.]
Correct? True


### A 1D transpose stays 1D

In [76]:
vector = np.array([1, 2, 3])
print("vector:", vector.shape, "vector.T:", vector.T.shape)
# A 1D array has no separate row/column axes to swap; insert an axis first.
column_vector = vector[:, None]
print("Column:", column_vector.shape, "transposed:", column_vector.T.shape)

vector: (3,) vector.T: (3,)
Column: (3, 1) transposed: (1, 3)


## 11. Broadcasting · slides 31–34
Compare shapes **from the right**: dimensions must match or one must be 1.

### Scalar, column offsets, row offsets

In [77]:
table = np.arange(12).reshape(3, 4)
print("Original:\n", table)
# A scalar is reused at every position.
print("Add scalar:\n", table + 10)
# Shape (4,) aligns with the last axis of (3, 4).
print("Add per column:\n", table + np.array([10, 20, 30, 40]))
# Shape (3, 1) lets one offset repeat across each row.
print("Add per row:\n", table + np.array([100, 200, 300])[:, None])

Original:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Add scalar:
 [[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
Add per column:
 [[10 21 32 43]
 [14 25 36 47]
 [18 29 40 51]]
Add per row:
 [[100 101 102 103]
 [204 205 206 207]
 [308 309 310 311]]


In [78]:
a = np.array([[0, 0, 0], [10, 10, 10], [20, 20, 20], [30, 30, 30]])
b = np.array([0, 1, 2])
print("Shapes:", a.shape, b.shape)
# Treat (3,) as (1, 3); reuse b across the four rows.
print(a + b)

Shapes: (4, 3) (3,)
[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


In [79]:
column = np.array([0, 10, 20, 30])[:, None]
row = np.array([0, 1, 2])[None, :]
print("Shapes:", column.shape, row.shape)
# (4, 1) + (1, 3) gives (4, 3): one sum for each row-column pair.
print(column + row)

Shapes: (4, 1) (1, 3)
[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


In [80]:
# Predict: will (4, 3) + (2, 3) work?
bad = np.array([[0, 1, 2], [3, 4, 5]])
# The last axes match, but 4 and 2 are incompatible; catch the demo error.
try:
    a + bad
except ValueError as error:
    print(error)

operands could not be broadcast together with shapes (4,3) (2,3) 


### Predict which shapes work

In [81]:
shape_pairs = [((4, 3), (3,)), ((4, 3), (4,)),
               ((4, 3), (4, 1)), ((4, 1), (1, 3)),
               ((2, 3, 4), (3, 1))]
# Compare dimensions from the right; missing leading dimensions act like 1.
for left, right in shape_pairs:
    try:
        print(left, "+", right, "->", np.broadcast_shapes(left, right))
    except ValueError:
        print(left, "+", right, "-> incompatible")

(4, 3) + (3,) -> (4, 3)
(4, 3) + (4,) -> incompatible
(4, 3) + (4, 1) -> (4, 3)
(4, 1) + (1, 3) -> (4, 3)
(2, 3, 4) + (3, 1) -> (2, 3, 4)


### Center and standardize columns

In [82]:
data = np.array([[10., 100.], [20., 140.], [30., 180.]])
# Reduce down rows to obtain one mean per column: shape (2,).
means = data.mean(axis=0)
# One standard deviation per column; NumPy uses ddof=0 by default.
stds = data.std(axis=0)
# Subtract the matching column mean from every observation.
centered = data - means
# Divide by each column's std; constant columns would need separate handling.
standardized = centered / stds  # Both columns have nonzero std
print("Column means:", means)
print("Centered:\n", centered)
print("Standardized:\n", standardized)
print("Check means / stds:", standardized.mean(axis=0), standardized.std(axis=0))

Column means: [ 20. 140.]
Centered:
 [[-10. -40.]
 [  0.   0.]
 [ 10.  40.]]
Standardized:
 [[-1.22474487 -1.22474487]
 [ 0.          0.        ]
 [ 1.22474487  1.22474487]]
Check means / stds: [0. 0.] [1. 1.]


### A valid shape can still give the wrong meaning

In [83]:
square = np.array([[1, 2], [10, 20]])
row_offsets = np.array([100, 200])
# Both operations are valid, but shape determines which axis gets the offsets.
print("1D offsets act on columns:\n", square + row_offsets)
print("Column-shaped offsets act on rows:\n", square + row_offsets[:, None])

1D offsets act on columns:
 [[101 202]
 [110 220]]
Column-shaped offsets act on rows:
 [[101 102]
 [210 220]]


## 12. Distances without loops · slide 35
One row = one point. Find distances between corresponding rows.

In [84]:
# Each array contains five points; each row holds (x, y).
l1 = np.array([[0, 0], [2, 0], [4, 0], [6, 0], [8, 0]])
l2 = np.arange(10).reshape(5, 2)
print("Line 1:\n", l1)
print("Line 2:\n", l2)

Line 1:
 [[0 0]
 [2 0]
 [4 0]
 [6 0]
 [8 0]]
Line 2:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [85]:
distances_loop = []
# zip pairs corresponding rows, rather than every possible pair.
for p, q in zip(l1, l2):
    distances_loop.append(np.sqrt((p[0] - q[0])**2 + (p[1] - q[1])**2))

# Subtract coordinates within each point pair: shape (5, 2).
diff = l1 - l2
# Square coordinate differences and sum across x/y: shape (5,).
squared_distances = (diff**2).sum(axis=1)
# Take a square root to convert squared distances to Euclidean distances.
distances = np.sqrt(squared_distances)
print("Shapes:", diff.shape, squared_distances.shape, distances.shape)
print("Loop:", distances_loop)
print("Vectorized:", distances)
print("Same?", np.allclose(distances_loop, distances))

Shapes: (5, 2) (5,) (5,)
Loop: [np.float64(1.0), np.float64(3.0), np.float64(5.0), np.float64(7.0), np.float64(9.0)]
Vectorized: [1. 3. 5. 7. 9.]
Same? True


### Extension: all pairwise distances

In [86]:
points = np.array([[0., 0.], [3., 0.], [0., 4.]])
# (3, 1, 2) minus (1, 3, 2) broadcasts to (3, 3, 2).
delta = points[:, None, :] - points[None, :, :]
# Reduce the coordinate axis; entry (i, j) is the distance from point i to j.
pairwise = np.sqrt((delta**2).sum(axis=2))
print("Intermediate shape:", delta.shape)  # Point i x point j x coordinate
print("Pairwise distances:\n", pairwise)

Intermediate shape: (3, 3, 2)
Pairwise distances:
 [[0. 3. 4.]
 [3. 0. 5.]
 [4. 5. 0.]]


## 13. Quick practice · slide 36
For `a` below: select the last two columns, keep even values, compute row sums, then subtract each column mean.

In [87]:
a = np.arange(1, 13).reshape(3, 4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [88]:
# Try here before revealing the next cell.

In [89]:
# SOLUTION — run after students try the practice.
# Keep all rows and the last two columns.
print(a[:, -2:])
# A remainder of zero identifies even values.
print(a[a % 2 == 0])
# Sum over columns to obtain one result per row.
print(a.sum(axis=1))
# The column means have shape (4,), so they broadcast across all rows.
print(a - a.mean(axis=0))

[[ 3  4]
 [ 7  8]
 [11 12]]
[ 2  4  6  8 10 12]
[10 26 42]
[[-4. -4. -4. -4.]
 [ 0.  0.  0.  0.]
 [ 4.  4.  4.  4.]]


## 14. Ufuncs and statistics · slides 37–38

In [90]:
a = np.array([1., 4., 9.])
print("sqrt:", np.sqrt(a))
# np.log is the natural logarithm, applied elementwise.
print("log:", np.log(a))
# np.exp computes e raised to each input value.
print("exp:", np.exp(np.array([0., 1., 2.])))

sqrt: [1. 2. 3.]
log: [0.         1.38629436 2.19722458]
exp: [1.         2.71828183 7.3890561 ]


### More elementwise functions

In [91]:
values = np.array([-2., -0.5, 0., 1.5, 3.])
print("Absolute:", np.abs(values))
# Ties round to the nearest even integer: -0.5 -> -0.0; 1.5 -> 2.0.
print("Round:", np.round(values))
# Replace values below 0 with 0 and above 2 with 2.
print("Clip to [0, 2]:", np.clip(values, 0, 2))
# Trigonometric functions use radians, not degrees.
angles = np.array([0., np.pi / 2, np.pi])
print("Sine:", np.sin(angles))

Absolute: [2.  0.5 0.  1.5 3. ]
Round: [-2. -0.  0.  2.  3.]
Clip to [0, 2]: [0.  0.  0.  1.5 2. ]
Sine: [0.0000000e+00 1.0000000e+00 1.2246468e-16]


In [92]:
# A fixed seed makes this demo reproducible when the cell is rerun.
rng = np.random.default_rng(0)
dice = rng.integers(1, 7, size=10)          # 1 through 6
errors = rng.normal(loc=0, scale=1, size=10) # scale = standard deviation
print("Dice:", dice)
print("Normal samples:", errors)
print("Mean:", dice.mean())
# ddof=0 uses N in the variance denominator; ddof=1 uses N-1.
print("Std (ddof=0):", dice.std())
print("Std (ddof=1):", dice.std(ddof=1))
print("25th percentile:", np.percentile(dice, 25))

Dice: [6 4 4 2 2 1 1 1 2 5]
Normal samples: [ 0.36159505  1.30400005  0.94708096 -0.70373524 -1.26542147 -0.62327446
  0.04132598 -2.32503077 -0.21879166 -1.24591095]
Mean: 2.8
Std (ddof=0): 1.7204650534085253
Std (ddof=1): 1.8135294011647258
25th percentile: 1.25


### Reproducible sampling and sample shape

In [93]:
# Same seed and same sequence of calls give the same pseudo-random samples.
rng1 = np.random.default_rng(42)
rng2 = np.random.default_rng(42)
print("Same seed:", rng1.integers(0, 10, 5), rng2.integers(0, 10, 5))
rng = np.random.default_rng(7)
# size=(2, 3) requests six samples arranged in two rows.
print("Normal array:\n", rng.normal(loc=10, scale=2, size=(2, 3)))
# replace=False prevents selecting the same position more than once.
print("Without replacement:", rng.choice(np.arange(10), size=4, replace=False))

Same seed: [0 7 6 4 4] [0 7 6 4 4]
Normal array:
 [[10.00246031 10.59749108  9.45172429]
 [ 8.21881632  9.09065843  8.01670689]]
Without replacement: [0 8 4 6]


### More summaries and missing values

In [94]:
values = np.array([1., 2., 3., 4., 10.])
print("Mean / median:", values.mean(), np.median(values))
# var() uses ddof=0 by default, matching std() squared.
print("Variance:", values.var())
print("Quartiles:", np.percentile(values, [25, 50, 75]))
# percentile uses 0-100; quantile uses 0-1.
print("Same quartiles:", np.quantile(values, [0.25, 0.5, 0.75]))
with_missing = np.array([1., np.nan, 3.])
# An ordinary mean propagates NaN; nanmean ignores missing entries.
print("mean / nanmean:", with_missing.mean(), np.nanmean(with_missing))

Mean / median: 4.0 3.0
Variance: 10.0
Quartiles: [2. 3. 4.]
Same quartiles: [2. 3. 4.]
mean / nanmean: nan 2.0


## 15. Final check
For a 3-by-4 array, predict the shapes below. Then filter rows whose mean is at least 6.

In [95]:
check = np.arange(12).reshape(3, 4)
print(check.sum(axis=0).shape)
print(check[:, 0].shape)
print(check[:, 0:1].shape)
print((check + np.arange(4)).shape)
# Try the row filter here.

(4,)
(3,)
(3, 1)
(3, 4)


**Solution — run after discussing.**

In [96]:
# Compute one mean per row, compare to 6, then apply the resulting row mask.
print(check[check.mean(axis=1) >= 6])

[[ 8  9 10 11]]
